<?php
$__config['route'] = [
    '' => 'client/home/index',
    '/' => 'client/home/index',
    '(.+)' =>  'client/home/index/$1',
    'home' => 'client/home/index',
    'home/getAnimeInfo' => 'client/home/getAnimeInfo',
    'home/getAnimeInfo/(.+)' => 'client/home/getAnimeInfo/$1',

    'description' => 'client/description/index',
    'description/(.+)' => 'client/description/index/$1',

    'watch' => 'client/watch/index',
    'watch/(.+)' => 'client/watch/index/$1',
    'watch/(.+)-(.+)-episode-(.+)' => 'client/watch/index/$1/$2/$3',


    'admin' => 'admin/dashboard/category',
    'admin/(.+)' => 'admin/dashboard/category/$1',
    'admin/category' => 'admin/dashboard/category',
    'admin/category/(.+)' => 'admin/dashboard/category/$1',
    'admin/addCategory' => 'admin/dashboard/addCategory',
    'admin/addCategory/(.+)' => 'admin/dashboard/addCategory/$1',
    'admin/deleteCategory' => 'admin/dashboard/deleteCategory',
    'admin/deleteCategory/(.+)' => 'admin/dashboard/deleteCategory/$1',
    'admin/showCategory' => 'admin/dashboard/showCategory',
    'admin/showCategory/(.+)' => 'admin/dashboard/showCategory/$1',

    'admin/genre' => 'admin/dashboard/genre',
    'admin/genre/(.+)' => 'admin/dashboard/genre/$1',
    'admin/addGenre' => 'admin/dashboard/addGenre',
    'admin/addGenre/(.+)' => 'admin/dashboard/addGenre/$1',
    'admin/deleteGenre' => 'admin/dashboard/deleteGenre',
    'admin/deleteGenre/(.+)' => 'admin/dashboard/deleteGenre/$1',
    'admin/showGenre' => 'admin/dashboard/showGenre',
    'admin/showGenre/(.+)' => 'admin/dashboard/showGenre/$1',
    'admin/getCategory' => 'admin/dashboard/getCategory',
    'admin/getCategory/(.+)' => 'admin/dashboard/getCategory/$1',

    'admin/anime' => 'admin/dashboard/anime',
    'admin/anime/(.+)' => 'admin/dashboard/anime/$1',
    'admin/addAnime' => 'admin/dashboard/addAnime',
    'admin/addAnime/(.+)' => 'admin/dashboard/addAnime/$1',
    'admin/deleteAnime' => 'admin/dashboard/deleteAnime',
    'admin/deleteAnime/(.+)' => 'admin/dashboard/deleteAnime/$1',
    'admin/showAnime' => 'admin/dashboard/showAnime',
    'admin/showAnime/(.+)' => 'admin/dashboard/showAnime/$1',
    'admin/getGenre' => 'admin/dashboard/getGenre',
    'admin/getGenre/(.+)' => 'admin/dashboard/getGenre/$1',

    'admin/episode' => 'admin/dashboard/episode',
    'admin/episode/(.+)' => 'admin/dashboard/episode/$1',
    'admin/addEpisode' => 'admin/dashboard/addEpisode',
    'admin/addEpisode/(.+)' => 'admin/dashboard/addEpisode/$1',
    'admin/deleteEpisode' => 'admin/dashboard/deleteEpisode',
    'admin/deleteEpisode/(.+)' => 'admin/dashboard/deleteEpisode/$1',
    'admin/showEpisode' => 'admin/dashboard/showEpisode',
    'admin/showEpisode/(.+)' => 'admin/dashboard/showEpisode/$1',
    'admin/getAnime' => 'admin/dashboard/getAnime',
    'admin/getAnime/(.+)' => 'admin/dashboard/getAnime/$1',

    'signout' => 'login/signout',
    'signout/(.+)' => 'login/signout/$1',
    'signin' => 'login/signin',
    'signin/(.+)' => 'login/signin/$1',
    'signup' => 'login/signup',
    'signup/(.+)' => 'login/signup/$1',
];
